version: "3.7"
services:
  curity:
    container_name: idsvr
    environment:
      PASSWORD: Secr3t
    image: curity/idsvr
    ports:
      - "6749:6749"
      - "4466:4466"
    networks:
      demonetwork:
        aliases:
          - idsvr

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      demonetwork:
        aliases:
          - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - type: bind
        source: ./config/grafana/dashboard.json
        target: /var/lib/grafana/dashboards/curity/idsvr-dashboard.json
    networks:
      demonetwork:
        aliases:
          - grafana

networks:
  demonetwork:
    name: metrics-demo-net
