{
 "title": "Curity Identity Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "prometheus" },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(idsvr_cpu_usage, instance)"
    }
   },
   {
    "name": "idsvr_instances",
    "query": {
     "query": "label_values(idsvr_cpu_usage, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary - All instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Authentications",
   "type": "stat",
   "description": "The number of authentication events raised by all instances during the dashboard time.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(idsvr_authentication_login_total[$__range]))",
     "legendFormat": "{{acr}}"
    }
   ]
  },
  {
   "title": "SSO",
   "type": "stat",
   "description": "The number of SSO events raised by all instances during the dashboard time.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(idsvr_authentication_sso_total[$__range]))",
     "legendFormat": "{{acr}}"
    }
   ]
  },
  {
   "title": "Tokens Issued",
   "type": "stat",
   "description": "The number of all oauth tokens issued by all instances during the dashboard time.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(idsvr_oauth_token_issued_total[$__range]))",
     "legendFormat": "{{token_type}}"
    }
   ]
  },
  {
   "title": "Introspections denied",
   "type": "stat",
   "description": "The number of Introspections denied because of tokens not being active, by all instances during the dashboard time.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(idsvr_oauth_introspection_denied_total[$__range]))",
     "legendFormat": "{{token_type}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Indicates if all the instances are up and running",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{instance=~\"$idsvr_instances\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Indicates if any of the instances logged an error.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(log4j2_appender_total{level=~\"error|fatal\", instance=~\"$idsvr_instances\"})"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "stat",
   "description": "Indicates if there were any debug or trace logs detected on any of the instances in an interval of 5 minutes. As a result it will take at a minimum 5 minutes after you disabled the logs until this flag changes.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"debug|trace\", instance=~\"$idsvr_instances\"}[5m])))"
    }
   ]
  },
  {
   "title": "Status $Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Indicates if the server is up and running",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Indicates if there were any error logs detected. Reset the metrics if the error was resolved.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(log4j2_appender_total{level=~\"error|fatal\", instance=~\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "stat",
   "description": "Indicates if there were any debug or trace logs detected on this instance in an interval of 5 minutes. As a result it will take at a minimum 5 minutes after you disabled the logs until this flag changes.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"debug|trace\", instance=~\"$Instance\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 6 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Last reported CPU usage in percent",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idsvr_cpu_usage{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Last reported total memory usage in MiB",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(idsvr_jvm_memory_used{instance=~\"$Instance\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "bargauge",
   "description": "Shows the number of log entries by their type",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "log4j2_appender_total{instance=~\"$Instance\"}",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{level}}@{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Shows the CPU usage in percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "idsvr_cpu_usage{instance=~\"$Instance\"}",
     "legendFormat": "CPU Usage@{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows the memory usage in mb",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "idsvr_jvm_memory_used{instance=~\"$Instance\"}",
     "legendFormat": "{{memory_area}} {{memory_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Timing",
   "type": "timeseries",
   "description": "Shows the average time in seconds that it takes to process an HTTP request. This includes requests to admin and runtime nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(idsvr_http_server_request_time_sum{instance=~\"$Instance\"}[$__rate_interval])/rate(idsvr_http_server_request_time_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "HTTP requests@{{instance}}"
    }
   ]
  },
  {
   "title": "DAP Timing",
   "type": "timeseries",
   "description": "Shows the average time in seconds that it takes to process datasource queries. Grouped by datasource type and instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_account_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_account_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "account@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_attribute_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_attribute_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "attribute@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_bucket_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_bucket_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "bucket@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_credential_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_credential_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "credential@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_dcr_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_dcr_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "DCR@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_delegation_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_delegation_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "delegation@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_device_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_device_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "device@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_nonce_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_nonce_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "nonce@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_session_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_session_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "session@{{instance}}"
    },
    {
     "expr": "sum by (dap_id, instance) (rate(idsvr_datasource_token_sum{instance=~\"$Instance\"}[$__rate_interval])) / sum by (dap_id) (rate(idsvr_datasource_token_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "token@{{instance}}"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SSO Rate",
   "type": "timeseries",
   "description": "Shows the average increase of SSO events per second. Grouped by authentication method and instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(idsvr_authentication_sso_total{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{acr}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Login Rate",
   "type": "timeseries",
   "description": "Shows the average increase of login events per second. Grouped by authentication method and instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(idsvr_authentication_login_total{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{acr}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Issued Token Rate",
   "type": "timeseries",
   "description": "Shows the average increase of issued tokens per second. Grouped by token type and instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (token_type, instance) (rate(idsvr_oauth_token_issued_total{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{token_type}} token@{{instance}}"
    }
   ]
  },
  {
   "title": "Revoked Token Rate",
   "type": "timeseries",
   "description": "Shows the average increase of revoked tokens per second. Group by token type and instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (token_type, instance) (rate(idsvr_oauth_token_revoked_total{instance=\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{token_type}} token@{{instance}}"
    }
   ]
  },
  {
   "title": "Login Count",
   "type": "bargauge",
   "description": "Shows the absolute number of logins for an authenticator and instance during the given interval",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(idsvr_authentication_login_total{instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{acr}}"
    }
   ]
  }
 ]
}