{
 "title": "Curity Identity Server",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(up, instance)" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Authentications",
   "type": "singlestat",
   "description": "The number of authentication events raised by all instances during the interval.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    { "expr": "sum(authentication_login)", "legendFormat": "{{acr}}" }
   ]
  },
  {
   "title": "SSO",
   "type": "singlestat",
   "description": "The number of SSO events raised by all instances during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    { "expr": "sum(authentication_sso)", "legendFormat": "{{acr}}" }
   ]
  },
  {
   "title": "Tokens Issued",
   "type": "singlestat",
   "description": "The number fo all oauth tokens issued by all instances during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    { "expr": "sum(oauth_token_issued)", "legendFormat": "{{token_type}}" }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "Indicates if all the instances are up and running",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "min(up)" }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "description": "Indicates if there were any error logs detected on any of the instances",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(rate(log4j2_appender_total{level=\"error\", level=\"fatal\"}[1m]))"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "singlestat",
   "description": "Indicates if there were any debug or trace logs detected on any of the instances",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"debug|trace\"}[5m])))"
    }
   ]
  },
  {
   "title": "Status $Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "description": "Indicates if the server is up and running",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "singlestat",
     "description": "Indicates if there were any error logs detected",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"error|fatal\", instance=~\"$Instance\"}[1m])))"
      }
     ]
    },
    {
     "title": "Debug",
     "type": "singlestat",
     "description": "Indicates if there were any debug or trace logs detected on the instance",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"debug|trace\", instance=~\"$Instance\"}[1m])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "bargauge",
     "description": "Shows the number of log entries by their type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "log4j2_appender_total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{level}}@{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Status $Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "description": "Indicates if the server is up and running",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "singlestat",
     "description": "Indicates if there were any error logs detected",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"error|fatal\", instance=~\"$Instance\"}[1m])))"
      }
     ]
    },
    {
     "title": "Debug",
     "type": "singlestat",
     "description": "Indicates if there were any debug or trace logs detected on the instance",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(sum(rate(log4j2_appender_total{level=~\"debug|trace\", instance=~\"$Instance\"}[1m])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "bargauge",
     "description": "Shows the number of log entries by their type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "log4j2_appender_total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{level}}@{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Shows the CPU usage in percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cpu_usage{instance=~\"$Instance\"}",
     "legendFormat": "CPU Usage@{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Shows the memory usage in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_memory_used{instance=~\"$Instance\"}[1m])",
     "legendFormat": "{{memory_area}} {{memory_id}}@{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Timing",
   "type": "graph",
   "description": "Shows the time in seconds that it takes to process an HTTP request. This includes requests to admin and runtime nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_request_time_sum{instance=~\"$Instance\"}[1m])/rate(http_server_request_time_count{instance=~\"$Instance\"}[1m])",
     "legendFormat": "HTTP requests@{{instance}}"
    }
   ]
  },
  {
   "title": "DAP Timing",
   "type": "graph",
   "description": "Shows the time in seconds that it takes to process database queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (dap_id) (rate(datasource_account_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_account_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "account@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_attribute_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_attribute_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "attribute@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_bucket_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_bucket_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "bucket@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_credential_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_credential_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "credential@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_dcr_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_dcr_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "DCR@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_delegation_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_delegation_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "delegation@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_device_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_device_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "device@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_nonce_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_nonce_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "nonce@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_session_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_session_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "session@{{instance}}"
    },
    {
     "expr": "sum by (dap_id) (rate(datasource_token_sum{instance=~\"$Instance\"}[1m])) / sum by (dap_id) (rate(datasource_token_count{instance=~\"$Instance\"}[1m]))",
     "legendFormat": "token@{{instance}}"
    }
   ]
  },
  { "title": "Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "SSO Rate",
   "type": "graph",
   "description": "Shows the rate of SSO events.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(authentication_sso{instance=~\"$Instance\"}[1m])",
     "legendFormat": "{{acr}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Login Rate",
   "type": "graph",
   "description": "Shows the rate of login events.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(authentication_login{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{acr}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Issued Token Rate",
   "type": "graph",
   "description": "Shows the rate of issued tokens by their type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (token_type) (rate(oauth_token_issued{instance=\"$Instance\"}[1m]))",
     "legendFormat": "Issued {{token_type}} token @{{instance}}"
    }
   ]
  },
  {
   "title": "Revoked Token Rate",
   "type": "graph",
   "description": "Shows the rate of issued tokens by their type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (token_type) (rate(oauth_token_revoked{instance=\"$Instance\"}[1m]))",
     "legendFormat": "Revoked {{token_type}} token@{{instance}}"
    }
   ]
  }
 ]
}